name:               Sustain
description:        a one day conversation for open source software sustainers

markdown:           kramdown

plugins:
  - jekyll-sitemap

# permalinks
permalink:          pretty

sass:
  style:            compressed

# server
port:               8000
url:                https://sustainoss.org
encoding:           UTF-8
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
